### ISSUE TITLE
README needs to be updated to reflect the latest changes

### ISSUE THREAD

**Issue by MCUdude** [MCUdude/avrdude-test-script#12]
@stefanrueger made the script support an optional argument. Would you like to Update the README to reflect these changes?
When this is done, we may consider adding the script/this repo to the official *avrdudes* user. Perhaps also calling the repo `avrdude-testing` instead.

**Comment by stefanrueger** [comment]
> Update the README

I made the script self-documenting. So, all that the readme needs could be showing the output of `-?` or `-h`
```
$ avrdude_test_script.sh -h
Syntax: avrdude_test_script.sh {<opts>}
Function: test avrdude for certain programmer and part combinations
Options:
    -c <configuration spec>     additional configuration options used for all runs
    -d <sec>                    delay between test commands (default 4 seconds)
    -e <avrdude path>           set path of avrdude executable (default avrdude)
    -p <programmer/part specs>  can be used multiple times, overrides default tests
    -s                          skip EEPROM tests for bootloaders
    -? or -h                    show this help text
Example:
    $ avrdude_test_script.sh -d 0 -p "-c dryrun -p t13" -p "-c dryrun -p m4809"
```
We could consider adding a few examples in the `Usage()` function of the script, though.

> adding the script/this repo to the official avrdudes

Why not in the directory tools for avrdude? The test script might need changing with avrdude (just like the documentation of avrdude) and having different  repos for the test and avrdude will cause synchronisation and versioning trouble.

I'd like to suggest more changes
 - The suffix `_script.sh` is a bit of an overkill; how about calling the script `test-avrdude` (so that the test script doesn't start with `avrdude` easing command line completion for both)?
 - The indentation is a bit weird: the main for loop should be less indented by two spaces
 - Use [safer flash test files](https://github.com/avrdudes/avrdude/issues/1616#issuecomment-1903772566)
